config/routes.rb
Rails.application.routes.draw do
  resources :knowledgebase
  get 'search', to: "knowledgebase#search"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
class Point
    include ActiveGraph::Node
    # Properties
    property :title
    property :content, default: 'Insert content here'
    
    # Relations
    has_many :both, :links, type: :LINK, model_class: self, labels: false

    # Validations
    validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/knowledgebase_controller.rb
class KnowledgebaseController < ApplicationController
  before_action :set_point, only: [:show, :edit, :destroy]

  def index
    @count = Point.count
  end

  def search
    @keyword = request.params['query']
    @title_result = Point.where('result_point2.title =~ ?', '(?i).*'+@keyword+'.*')
    @content_result = Point.where('result_point2.content =~ ?', '(?i).*'+@keyword+'.*') 
  end

  def show
  end

  def edit    
  end

  def new
  end

  def update
    @p = Point.find(request.params['id'])
    point_params = params.permit(:title, :content, links: [])
    @p.title = point_params['title'] if !point_params['title'].nil?
    @p.content = point_params['content'] if !point_params['content'].nil?
    @p.links = nil
    @p.links << Point.where(uuid: point_params['links'])
    @p.save

    flash[:notice] = "Successfully updated point!"
    redirect_to action: 'show', id: @p.uuid
  end

  def create
    point_params = params.permit(:title, :content, links: [])
    @p = Point.create(title: point_params['title'], content: point_params['content'])
    # insert links after saving because it's picky about connecting graph nodes before creating them
    @p.links << Point.where(uuid: point_params['links'])
    @p.save

    flash[:notice] = "Successfully created point!"
    redirect_to action: 'show', id: @p.uuid
  end

  def destroy
    @p.destroy
    flash[:notice] = "Successfully deleted point!"
    redirect_to action: 'index'
  end

  private
  def set_point
    @p = @p || Point.find(request.params['id'])
    @links = @p.links.pluck(:title, :uuid)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/knowledgebase_helper.rb
module KnowledgebaseHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/index.html.erb
<%= turbo_frame_tag "body" do %>
    <h1>Hello World</h1>
<% end %>

app/views/knowledgebase/edit.html.erb
<%= form_with url: "/knowledgebase/"+@p.uuid, method: :patch do |form| %>

<header class="flex justify-between">
    <input type="text" name="title" class="block w-full border-0 border-b-2 border-gray-200 focus:ring-0 focus:border-black mb-8 mr-8 text-3xl" placeholder="" value="<%= @p.title %>">
    <div>
        <%= form.submit "Update", class:"bg-green-400 hover:bg-green-300 focus:outline-none text-white py-2 px-4 rounded-md size-xl" %>
    </div>
</header>

<!-- Links -->
<div class="mb-4">
    <h2 class="text-xl mb-2"> Links </h2>  
    <select class="select2 w-1/2" name="links[]" multiple="multiple">
        <%  Point.all.each{ |p|  %>
            <% next if p.uuid == @p.uuid %>
            <option value="<%= p.uuid %>" <%= @links.map{|l| l[1]}.include?(p.uuid) ? 'selected="selected"' : '' %> > <%= p.title %> </option>
        <%  } %>
    </select>

</div>

<%= form.rich_text_area :content, value: @p.content %>

<% end %>

app/views/knowledgebase/index.html.erb
<h1>Knowledgebase</h1>

<div class="container w-full h-full flex flex-col justify-center items-center ">

    <a href="<%= "/knowledgebase/new" %>">
        <button class="bg-green-400 hover:bg-green-300 focus:outline-none text-white py-2 px-4 rounded-md text-3xl mb-4">Create</button>
    </a>
    <h4 class="text-l text-gray-600">There are currently <%= @count %> entries listed</h4>
    <h2 class="text-2xl m-4">Search the knowledgebase</h2>

    <%= form_with url: "/search", class: "w-1/2 ", method: :get do |form| %>
        <%= form.text_field :query, placeholder: "search...", class: "w-full rounded", html: { type:"search" } %>
        <%= form.submit "Search", class: "hidden" %>
    <% end %>
</div>

app/views/knowledgebase/new.html.erb
<%= form_with url: "/knowledgebase", method: :post do |form| %>

<header class="flex justify-between">
    <input type="text" name="title" class="block w-full border-0 border-b-2 border-gray-200 focus:ring-0 focus:border-black mb-8 mr-8 text-3xl" placeholder="Title..." value="">
    <div>
        <%= form.submit "Create", class:"bg-green-400 hover:bg-green-300 focus:outline-none text-white py-2 px-4 rounded-md size-xl" %>
    </div>
</header>

<!-- Links -->
<div class="mb-4">
    <h2 class="text-xl mb-2"> Links </h2>  
    <select class="select2 w-1/2" name="links[]" multiple="multiple">
        <%  Point.all.each{ |p|  %>
            <option value="<%= p.uuid %>" > <%= p.title %> </option>
        <%  } %>
    </select>

</div>

<%= form.rich_text_area :content %>

<% end %>

app/views/knowledgebase/search.html.erb
<h1 class="mb-8">Knowledgebase - Search Results</h1>
<h2 class="text-3xl">Title results:</h2>
<%
    if @title_result.empty?
%>
        <h2 class="text-gray-400 my-2 ml-4">No Results</h2>
<%
    else
        @title_result.each { |r| %>
            <%= link_to r.title,  "knowledgebase/"+r.uuid, class: "hover:text-blue-500 text-xl my-2 ml-4 block" %>
        <% }
    end
%>

<h2 class="text-3xl">Content results:</h2>
<%
    if @content_result.empty?
%>
        <h2 class="text-gray-400 my-2 ml-4">No Results</h2>
<%
    else
        @content_result.each { |r| %>
            <%= link_to r.title,  "knowledgebase/"+r.uuid, class: "hover:text-blue-500 text-xl my-2 ml-4 block" %>
        <% }
    end
%>

app/views/knowledgebase/show.html.erb
<header class="flex justify-between">
    <!-- Title -->
    <h1 class="mb-8"> <%= @p.title %> </h1>
    <!-- Buttons -->
    <div>
        <%= link_to 'Delete',
                knowledgebase_path(@p.uuid), 
                class: 'bg-red-400 hover:bg-red-300 focus:outline-none text-white py-2 px-2 rounded-md size-xl mx-6',
                method: :delete,
                data: { confirm: "Are you sure?" } %>
        <a href="<%= "/knowledgebase/"+@p.uuid+"/edit" %>">
            <button class="bg-green-400 hover:bg-green-300 focus:outline-none text-white py-2 px-4 rounded-md size-xl">Edit</button>
        </a>
    </div>
</header>
<!-- Links -->
    <% if !@links.empty? %>
    <hr class="mb-4"/>
    <div>
        <h2 class="text-xl mb-2"> Links </h2>  
        <ul class="w-full flex flex-wrap justify-start">
    <%  @links.each{ |l|  %>
        <li class="hover:text-blue-500 my-2 mx-4"> <%= link_to l[0] , knowledgebase_path(l[1]) %> </li>
    <%  } %>
        </ul>
    </div>
    <% end %>
<hr class="mb-4"/>
<!-- Content -->
<div class="content">
    <%= @p.content.html_safe %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="min-h-screen">
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@300;400;600;800&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="min-h-screen flex">

    <side class="w-64 p-8 bg-blue-100 min-h-screen block">
      <ul>
        <!-- <li class="hover:text-blue-500 font-semibold"> <%= link_to "Home" , root_url, data: {"turbo-frame": :"body"} %> </li> -->
        <li class="hover:text-blue-500 font-semibold"> <%= link_to "Home" , root_url %> </li>
        <li class="hover:text-blue-500 font-semibold"> <%= link_to "Knowledgebase" , knowledgebase_index_path %> </li>
      </ul>
    </side>

    <div class="container mx-auto p-8">
      <% if notice %>
        <p class="notice bg-green-100 p-4 rounded-xl mb-4"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert bg-red-100 p-4 rounded-xl mb-4"><%= alert %></p>
      <% end %>
       <%#  turbo_frame_tag "body" do %>
        <%= yield %>
      <%# end %>
    </div>

  </body>
</html>